### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by howy1993** [spacemeshos/testnet-issues#1]
**Describe the Issue**
Minor typo

**To Reproduce**
On testnet guide page: https://testnet.spacemesh.io/#/guide/setup

**Result**
Text says "100GB, 20Gb, 300GB" 

**Expected behavior**
It should be either "100GB, 200GB, 300GB" or "20GB, 100GB, 300GB" 

**Screenshots**
<img width="1260" alt="Screen Shot 2020-02-15 at 5 30 49 PM" src="https://user-images.githubusercontent.com/19526231/74597236-167e4580-5019-11ea-8225-bf11bc25e7e0.png">

**Comment by avive** [comment]
Thank you - fixed - reload the page.
